const locations = [
  "Abdukarim",
  "Ahmad Yassaviy",
  "Alaja",
  "Alamli",
  "Altinko'l (Qo'ng'irot tumani)",
  "Andijon",
  "Angor",
  "Angren",
  "Arsif",
  "Asaka",
  "Avval",
  "Babalakota",
  "Baliqchi",
  "Balta",
  "Bardanko'l",
  "Baynalmilal",
  "Bekat",
  "Bekobod",
  "Bekobod (Bog'dod tumani)",
  "Beruni",
  "Beruniy (Qiyichirchiq tumani)",
  "Beshariq",
  "Beshkapa",
  "Beshkent",
  "Beshrabod",
  "Bo'jay",
  "Bo'ka",
  "Bo'rbaliq",
  "Bo'ston",
  "Bo'ston (Oltinsoy tumani)",
  "Bo'ston (Ellikqali tumani)",
  "Bo'ston (Zarbdor tumani)",
  "Bog'iturkon",
  "Bog'ot",
  "Bogdan",
  "Boyovut",
  "Boysun",
  "Buloqboshi",
  "Bulung'ur",
  "Burchmullo",
  "Buvayda",
  "Buxoro",
  "Bоg'dod",
  "Changi",
  "Chelak",
  "Chimboy",
  "Chimyon",
  "Chinabod",
  "Chinoz",
  "Chirchiq",
  "Chiroqchi",
  "Cho'rindi",
  "Chorbog'",
  "Chorraha",
  "Chortoq",
  "Chortoq (Guliston tumani)",
  "Chorvoq",
  "Chulkuvar",
  "Chust",
  "Chuvalachi",
  "Dang'ara",
  "Dangir",
  "Dasht",
  "Dashtobod",
  "Dehoji",
  "Dehqonobod",
  "Denov",
  "Denov (Shafirqon tumani)",
  "Do'rmon",
  "Do'stlik",
  "Do'stlik (Denov tumani)",
  "Do'stobod",
  "Dusimbiy",
  "Egizbuloq",
  "Eshmatoul",
  "Eshonguzor",
  "Fargʻona",
  "Farxod",
  "Fayziobod",
  "Forish",
  "Furqat",
  "G'alaba",
  "G'allaorol",
  "G'azalkent",
  "G'o's",
  "G'oliblar",
  "G'uzor",
  "Gagarin",
  "Galaosiya",
  "Galaquduq",
  "Gijduvon",
  "Gul",
  "Gulbahor",
  "Guliston",
  "Guliston (Yuqorichirchiq tumani)",
  "Gullanbog'",
  "Gulobod",
  "Gulzar",
  "Gulzar (Paxtakor tumani)",
  "Gurlan",
  "Hamzaobod",
  "Hayit",
  "Hisorak",
  "Humson",
  "Ibrat",
  "Iftixor",
  "Ishtixon",
  "Ispanza",
  "Istiqlol",
  "Ittifoq",
  "Jalaquduq",
  "Jambul",
  "Jarqo'rg'on",
  "Jayraxona",
  "Jilva",
  "Jizzax",
  "Jizzaxlik",
  "Jo'ynav",
  "Jomboy",
  "Jondor",
  "Juma",
  "Jumabazar (Bekobod tumani)",
  "Jumabazar (Yuqori Chirchiq tumani)",
  "Jumashuy",
  "Jurek",
  "Juren",
  "Kakaydi",
  "Kangli",
  "Kanimex",
  "Kaptarxona",
  "Karamaz",
  "Karkidan",
  "Karmana",
  "Katta Ramadon",
  "Kattaqo'rg'on",
  "Kegayli",
  "Kelauchi",
  "Keles",
  "Kitob",
  "Ko'hna Kalon",
  "Ko'hna Sho'rcha",
  "Ko'kdala",
  "Ko'ksaroy",
  "Kogon",
  "Kosari",
  "Koson",
  "Kosonsoy",
  "Krasnogorsk",
  "Kulonxona",
  "Kumarik",
  "Kuyganyor",
  "Kuyun",
  "Labiro'd",
  "Lagan",
  "Lagandi",
  "Lalmiqor",
  "Lolazor",
  "Loyish",
  "Madaniyat",
  "Malikrabot",
  "Mang'it",
  "Margʻilon",
  "Marhamat",
  "Marjonbuloq",
  "Markaz",
  "Mashak",
  "Mindon",
  "Misr",
  "Muborak",
  "Mug'lon",
  "Mulkanlik",
  "Mulloyon",
  "Muratali",
  "Mustaqillik",
  "Namangan",
  "Namdanak",
  "Namuna",
  "Nanay",
  "Narpay (Karmana tumani)",
  "Navbahor",
  "Navbahor (Namangan tumai)",
  "Navoiiy",
  "Navoiy",
  "Navro'z",
  "Nazarbek",
  "Niyozbash",
  "Novaboshi",
  "Novkent",
  "Novmetan",
  "Nukus",
  "Nurafshon",
  "Nurobod",
  "Nurobod (Ohangaron tumani)",
  "Nurota",
  "O'rta Oqchi",
  "O'zbekiston",
  "Ohangaron",
  "Olimkent",
  "Olmaliq",
  "Olmazor (Chinoz tumani)",
  "Olot",
  "Oltiariq",
  "Oltinariq",
  "Oltinko'l",
  "Oqmang'it",
  "Oqoltin",
  "Oqqo'rg'on",
  "Oqtosh",
  "Ozod Vatan (Muzrobod tumani)",
  "Parchanxas",
  "Pargos",
  "Parkent",
  "Paxta (Chinoz tumani)",
  "Paxtachi",
  "Paxtakor",
  "Paxtaobod",
  "Paxtaobod (Sardoba tumani)",
  "Paxtazor",
  "Payariq",
  "Payshanba",
  "Pishagar",
  "Piskent",
  "Pitnak",
  "Pop",
  "Povulgon",
  "Poytug'",
  "Pushmon",
  "Qahramon",
  "Qamashi",
  "Qanliko'l",
  "Qaqir",
  "Qaravul",
  "Qarshi",
  "Qashqari",
  "Qatartol",
  "Qibray",
  "Qiziltepa",
  "Qo'g'ali",
  "Qo'ng'irot",
  "Qo'qon",
  "Qo'qonboy",
  "Qo'rg'oncha",
  "Qo'rg'ontepa",
  "Qo'shkupir",
  "Qo'shqo'rg'on",
  "Qo'shrobod",
  "Qo'shtepa",
  "Qora Xitoy",
  "Qoraboy",
  "Qorako'l",
  "Qoranko'l",
  "Qorao'zak",
  "Qoraqo'yli",
  "Qoraqushchi",
  "Qoraqushxona",
  "Qorashina",
  "Qorasuv",
  "Qorasuv (Paxtaobod tumani)",
  "Qorayantoq",
  "Qorovulbozor",
  "Qosh Yog'och",
  "Quduqcha",
  "Qumariqobod",
  "Qumqo'rg'on",
  "Qurama (Oltinsoy tumani)",
  "Qurbonov",
  "Quva",
  "Quvasoy",
  "Quyaboshi",
  "Rapqon",
  "Rishton",
  "Romitan",
  "Rovot",
  "Sabzikor",
  "Salar",
  "Samarqand",
  "Samarqandquduq",
  "Sanam",
  "Sang",
  "Sarbozor",
  "Sardoba",
  "Sariasiya",
  "Sarik (Qiziriq tumani)",
  "Saritepa",
  "Sasbaka",
  "Sayxun",
  "Shahrisabz",
  "Shahrixon",
  "Shamaton",
  "Shampan",
  "Sherobod",
  "Shirin",
  "Sho'ralisoy",
  "Sho'rchi",
  "Shodlik",
  "Shodlik (Oqoltin tumani)",
  "Shofirkon",
  "Shoyimbek",
  "Shumanay",
  "Shоvоt",
  "Sijjak",
  "Sirdaryo",
  "So'fon",
  "So'lti",
  "Sohibkor",
  "Sohil",
  "Soyliq",
  "Sukok",
  "Sulton Segizboyev",
  "Sutkibuloq",
  "Talkok",
  "Taxiatosh",
  "Taxtako'pir",
  "Teraktagi",
  "Termez",
  "Timiryazev",
  "Tinchlik",
  "To'qboy",
  "To'raqo'rg'on",
  "To'rtko'l",
  "Toshbuloq",
  "Toshkent",
  "Toshloq",
  "Toshloq (Qiyichirchiq tumani)",
  "Toyloq",
  "Turkmen",
  "Tuyabo'g'iz",
  "Uchko'prik",
  "Uchqizil",
  "Uchqo'rg'on",
  "Uchquduq",
  "Uchtepa",
  "Ulug'bek",
  "Umar",
  "Unqo'rg'on",
  "Unxayat",
  "Uramas",
  "Urganch",
  "Urgut",
  "Usmat",
  "Usmon Nosir",
  "Uychi",
  "Uyrat",
  "Uzun",
  "Vobkent",
  "Vodil",
  "Xalkobod",
  "Xalkobod (Yangiyo'l tumani)",
  "Xalkobod (Kegayli tumani)",
  "Xanka",
  "Xaqqulobod",
  "Xazarasp",
  "Xitoyan",
  "Xiva",
  "Xo'ja Yaqshba",
  "Xo'jaobod",
  "Xo'jarabot",
  "Xo'jasoat",
  "Xo'jayli",
  "Xo'jikent (Bo'stonliq tumani)",
  "Xonbandi",
  "Xonobod",
  "Xonziq",
  "Xorkash",
  "Xos",
  "Xovos",
  "Xusnobod",
  "Yakkabog'",
  "Yallama",
  "Yangi Chinoz (Chinoz tumani)",
  "Yangi Marg'ilon",
  "Yangi Mirishkar",
  "Yangi Nishon",
  "YangiHayot (Qiyichirchiq tumani)",
  "Yangiarik",
  "Yangibozor",
  "Yangibozor (Peshku tumani)",
  "Yangibоzоr (Yangibоzоr tumani)",
  "Yangiobod",
  "Yangiobod (Bo'ka tumani)",
  "Yangiovul",
  "Yangiqo'rg'on",
  "Yangirabat",
  "Yangiyer",
  "Yangiyo'l",
  "Yarkin",
  "Yaypan",
  "Yom",
  "Yozyovon",
  "Yuqori Bachqir",
  "Yuqori Valik",
  "Zafar",
  "Zafarobod",
  "Zafarobod (Konimex tumani)",
  "Zangiota",
  "Zarafshon",
  "Zarbdor",
  "Zarkent",
  "Zavrok",
  "Ziyodin",
  "Zomin",
  "Аyvalik",
];

export default locations;