import {
  img1,
  img2,
  img3,
  img4,
  img5,
  img6,
  img7,
  img8,
  img9,
} from "../assets/image";

const cardsDataBase = [
  {
    image: img1,
    bigSale: true,
    original: false,
    star: 4.9,
    comments: 30279,
    monthlyPayment: 5465,
    advancePayment: "Arzon narx kafolati",
    title: "PROKHVOST Mushuklar uchun konserva, losos va alabalk ta'mi, 415 gr",
  },
  {
    image: img2,
    bigSale: true,
    original: false,
    star: 4.9,
    comments: 7290,
    monthlyPayment: 8960,
    advancePayment: "40 990",
    title: "Крем Floresan F-100 против загара отбеливающий SPF 35, 125 млr",
  },
  {
    image: img3,
    bigSale: false,
    original: true,
    star: 4.8,
    comments: 30279,
    monthlyPayment: 2430,
    advancePayment: "Arzon narx kafolati",
    title: "Бумага листовая Svetocopy ECO, А4ф, 80г/м2, 500 листов",
  },
  {
    image: img4,
    bigSale: true,
    original: false,
    star: 4.9,
    comments: 30279,
    monthlyPayment: 1200,
    advancePayment: "Arzon narx kafolati",
    title: "Qog'oz Snegurochka, ofis, A4, 500 varaq",
  },
  {
    image: img5,
    bigSale: false,
    original: true,
    star: 4.9,
    comments: 2900,
    monthlyPayment: 1980,
    advancePayment: "Arzon narx kafolati",
    title:
      "Varaq qog'oz, ofis jihozlari uchun Sylvamo Svetocopy, A4f C07/3, 500 varaq",
  },
  {
    image: img5,
    bigSale: false,
    original: true,
    star: 4.8,
    comments: 168,
    monthlyPayment: 2305,
    advancePayment: "Arzon narx kafolati",
    title: "Garnier Skin Naturals Nozik teri uchun misellar suvi, 125 ml",
  },
  {
    image: img6,
    bigSale: true,
    original: false,
    star: 4.9,
    comments: 967,
    monthlyPayment: 3780,
    advancePayment: "Arzon narx kafolati",
    title:
      "Teymurova Oyoq dezodoranti spreyi, hid va terga qarshi, salitsil kislotali, 150 ml",
  },
  {
    image: img7,
    bigSale: true,
    original: true,
    star: 4.7,
    comments: 4502,
    monthlyPayment: 657,
    advancePayment: "40 990",
    title: "Qulay hazm qilish uchun sut aralashmasi Kabrita 2 Gold, 400 gr",
  },
  {
    image: img8,
    bigSale: false,
    original: false,
    star: 5.0,
    comments: 5493,
    monthlyPayment: 2143,
    advancePayment: "Arzon narx kafolati",
    title:
      "Ko'zoynak va gadjet ekranlari uchun Opticlean nam salfetkalari, 50 dona",
  },
  {
    image: img9,
    bigSale: false,
    original: false,
    star: 4.9,
    comments: 1535,
    monthlyPayment: 1980,
    advancePayment: "40 990",
    title:
      "Ayollar uchun dezodorant spreyi Nivea Pearl Beauty, marvarid ekstrakti bilan, 150 ml",
  },
];

export default cardsDataBase;
